name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linter-job:
    uses: ./.github/workflows/lint-job.yml
    with:
      branch_name: ${{ github.head_ref }}
